### ISSUE TITLE
HTML/SVG equivalent?

### ISSUE THREAD

**Issue by pspeter3** [faddee/csstype#1]
Is there a JSX equivalent to this for HTML & SVG?

**Comment by faddee** [comment]
Yes, what you're looking for is [`@types/react`](https://www.npmjs.com/package/@types/react) or equivalent to whatever library you're using.

**Comment by pspeter3** [comment]
Yeah, I know about them. I was actually hoping for a universal JSX type definition that can be unified across Picodom, Hyperapp, and Preact.
